--- 
- merb-core (= 1.0.1, runtime)
- extlib (>= 0.9.8, runtime)
- erubis (>= 2.6.2, runtime)
- rake (>= 0, runtime)
- json_pure (>= 0, runtime)
- rspec (>= 0, runtime)
- rack (>= 0, runtime)
- mime-types (>= 0, runtime)
- thor (>= 0.9.7, runtime)
- webrat (>= 0.3.1, development)
- merb-action-args (= 1.0.1, runtime)
- merb-assets (= 1.0.1, runtime)
- merb-helpers (= 1.0.1, runtime)
- merb-slices (= 1.0.1, runtime)
- merb-auth-core (= 1.0.1, runtime)
- merb-auth-more (= 1.0.1, runtime)
- dm-core (>= 0, runtime)
- merb-auth-slice-password (= 1.0.1, runtime)
- dm-aggregates (= 0.9.7, runtime)
- dm-migrations (= 0.9.7, runtime)
- dm-timestamps (= 0.9.7, runtime)
- dm-validations (= 0.9.7, runtime)
- dm-is-versioned (= 0.9.7, runtime)
- dm-is-nested_set (= 0.9.7, runtime)
- dm-is-state_machine (= 0.9.7, runtime)
- dm-tags (= 0.9.7, runtime)
- dm-paperclip (>= 0, runtime)
- will_paginate (= 2.5.0, runtime)
- merb_datamapper (= 1.0.1, runtime)
- merb-haml (= 1.0.1, runtime)
